### ISSUE TITLE
Necessidade de funções de callback onCloseClick, onOutsideClick

### ISSUE THREAD

**Issue by pedroespindula** [rogertavaress/react-brave-modal#4]
Oi @rogertavaress,

Encontramos uma necessidade de possuir funções de callback para quando se clicasse no botão de fechar, como também quando se clicasse fora do modal.

Ou seja, nesse botão destacado:

![image](https://user-images.githubusercontent.com/38431219/112201254-d1025380-8bee-11eb-82b5-e772fb2c52ed.png)

E fora do modal.

Acreditamos que passar funções dentro do objeto passado para o showModal, resolveria isso. Internamente, seria necessário escutar essas funções e chama-las no trigger do evento.

O que você acha?

Novamente, a nossa equipe está interessada em implementar isso o mais rápido possível, ou seja, nós mesmos abriríamos um PR com essa funcionalidade.

**Comment by rogertavaress** [comment]
Olá Pedro!

Essa funcionalidade foi implementada na versão mais recente (**v0.2.0**).

O problema foi que eu ainda não atualizei a documentação.

O objeto do showModal recebe as funções closeActionSync e closeAction.

No commit: https://github.com/rogertavaress/react-brave-modal/commit/23e663800505f671c67ba1bb993881829c3769b3

Obrigado.

**Comment by pedroespindula** [comment]
Tá ok, muito obrigado! Iremos tentar utilizar e qualquer dúvida adicional, falo contigo. Vou fechar essa issue e marca-la como resolvida.
